#pragma once
#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include <glm/glm/glm.hpp>
#include <glm/glm/gtc/matrix_transform.hpp>
#include <glm/glm/gtc/type_ptr.hpp>
#include <glm/glm/gtx/vector_angle.hpp>
#include <sgObject3D.h>
#include <sgCamera3D.h>
#include <sgSpotLight3D.h>
#include <sgUtils.h>
#include <sgRenderer.h>
#include <sgInputManager.h>